### PR TITLE
chore: Bump to Go1.22

### PR DESCRIPTION
**Pull request by aqstack**

### CODE REVIEW

**Review by ctlong — APPROVED** [review]

**Review by ctlong — DISMISSED** [review]
`src/otel-collector/go.mod` is a generated file. Did you update it manually? When I run the regenerate script I don't get this result.

**Comment by aqstack** [comment]
> `src/otel-collector/go.mod` is a generated file. Did you update it manually? When I run the regenerate script I don't get this result.

Yes, I added it manually after verifying what the regenerate script does. How about we add `go mod edit -go 1.22.0` command in the regenerate script. Snippet from the modified script:

```
 pushd "${release_dir}/src/otel-collector"
     go get toolchain@none
     go mod edit -go 1.22.0
     go mod tidy
     go mod vendor
 popd
```

**Comment by ctlong** [comment]
Why force the generated go.mod to have go1.22 set as the minimum? We would prefer for the minimum go version required to match the go version we're using, but it seems to me more of a nice-to-have than a requirement. And in that case, I don't think it's worth building in a workaround for the generated files.

What do you think?

**Comment by aqstack** [comment]
I agree, it's more of a nice-to-have than a requirement. I've reverted the manual change. Thanks for the feedback!

**Review by mkocher — APPROVED** [review]

**Pull request merged**
