### PR TITLE
Enable global port listening

### PR DESCRIPTION
**Pull request by jbooherl**
Add a property that enables the ability for external VMs to write to the Otel ingress porr

### CODE REVIEW

**Comment by acrmp** [comment]
Thanks @jbooherl!

Rather than using the boolean property, what if we instead just accepted an `ingress.grpc.listen_address` property so that we don't have to switch in the template?

We also have some template tests. Could you add an example for this case there?
https://github.com/cloudfoundry/otel-collector-release/blob/main/spec/support/shared_examples_for_otel_collector.rb

**Comment by jbooherl** [comment]
Sounds good, also question.. I'm not really a rubyer, when I run `bundle exec rspec` I get a lot of `unknown keyword: :aliases` Is there an easy was to fix this so I can run these tests in the future?

**Comment by ctlong** [comment]
@jbooherl it looks like @mkocher has incorporated this change into his PR: #13.

In that case, I think we can close out this PR, if that's alright with you?

**Comment by jbooherl** [comment]
Sounds good to me!

**Pull request closed without merging**
